### ISSUE TITLE
Sanic?

### ISSUE THREAD

**Issue by jonathan-s** [jsoucheiron/sync-vs-async#1]
You might want to take a look at Sanic :)

**Comment by jsoucheiron** [comment]
I might expand it to cover other frameworks, but I didn't have time :(.

Tornado and Sanic are definitely on my list

**Comment by jsoucheiron** [comment]
Sanic was added in my last commit.

**Comment by jonathan-s** [comment]
:)


*Jonathan Sundqvist*
Twitter <http://www.twitter.com/ecologythinking> | Linkedin
<http://se.linkedin.com/in/jonathansundqvist>

2017-11-02 15:27 GMT+01:00 Jordi Soucheiron <notifications@github.com>:
